# Site settings
title: Balls
tagline: 'Twisted tales to make you shudder' 
email: daniel@oshea.io
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
url: "http://oshea.io"
sidebar_image: /images/cover.jpg

# Build settings

permalink: pretty
markdown: redcarpet
highlighter: pygments
